name: Build

on: push

jobs:
  build:
    env:
      CI: true

    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm

      - name: NPM install
        run: npm ci

      - name: ESLint
        run: npm run lint

      - name: Build all
        run: npm run compile

      - name: Run tests
        run: npm run test
